[package]
name = "duckception"
version = "0.1.0"
authors = ["Ian Moody <imoody1@hotmail.com>"]
edition = "2018"

[features]
include_site = []

[dependencies]
hyper = "0.13"
tokio = { version = "0.2", features = ["full"] }
futures = { version = "0.3" }
# serde = {version = "1.0", features = ["derive"] }
# serde_json = "1.0"
# uuid = { version = "0.4", features = ["serde", "v4"] }
# warp = "0.2"
# rand = "0.7"
