[package]
name = "duckception"
version = "0.1.0"
edition = "2018"

[features]
include_site = []

[dependencies]
hyper = "0.13"
tokio = { version = "0.2", features = ["full"] }
futures = { version = "0.3" }
lazy_static = "1.4.0"
regex = "1.4.1"
uuid = { version = "0.8", features = ["v4"] }

# warp = "0.2"
# rand = "0.7"
# serde = {version = "1.0", features = ["derive"] }
# serde_json = "1.0"