[package]
name = "were_duck_server"
version = "0.1.0"
authors = ["Ian Moody <imoody1@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
