[package]
name = "terminal_client"
version = "0.0.0"
edition = "2018"

[dependencies]
log = "0.4.14"
env_logger = "0.8.3"
tungstenite = "0.13.0"
url = "2.2.1"
tui = "0.14"
termion = "1.5"

[dev-dependencies]